from dotenv import load_dotenv
import os

load_dotenv()

BOT_TOKEN = os.getenv("BOT_TOKEN")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
MINIAPP_URL = os.getenv("MINIAPP_URL")
EMPLOYEE_CHAT_ID = int(os.getenv("EMPLOYEE_CHAT_ID", 0))
OPENAI_PROXY = os.getenv("OPENAI_PROXY")
SQLALCHEMY_DATABASE_URL = os.getenv("SQLALCHEMY_DATABASE_URL")

AMO_CLIENT_ID = os.getenv("AMO_CLIENT_ID")
AMO_CLIENT_SECRET = os.getenv("AMO_CLIENT_SECRET")
AMO_REDIRECT_URI = os.getenv("AMO_REDIRECT_URI")
AMOCRM_ACCESS_TOKEN = os.getenv("AMOCRM_ACCESS_TOKEN")
AMOCRM_SUBDOMAIN = os.getenv("AMOCRM_SUBDOMAIN")

AMO_PIPELINE_ID = int(os.getenv("AMO_PIPELINE_ID", 0))
AMO_RESPONSIBLE_USER_ID = int(os.getenv("AMO_RESPONSIBLE_USER_ID", 0))
AMO_STATUS_ID = int(os.getenv("AMO_STATUS_ID", 0))
